# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'a9b92e0e-38fa-45fc-97c8-018714273196'
  imageRepository: 'fiegamitdockercomplex'
  containerRegistry: 'dockertestcr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/client/Dockerfile.dev'
  tag: '$(Build.BuildId)'
  REGISTRY_PASS: $(imageRegistryPassword)
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerTestCR'
        repository: 'fiegamitdockercomplex_client'
        command: 'buildAndPush'
        Dockerfile: 'client/Dockerfile'
        buildContext: 'client'
        tags: |
          $(Build.BuildId)
          latest
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerTestCR'
        repository: 'fiegamitdockercomplex_api'
        command: 'buildAndPush'
        Dockerfile: 'server/Dockerfile'
        buildContext: 'server'
        tags: |
          $(Build.BuildId)
          latest
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerTestCR'
        repository: 'fiegamitdockercomplex_worker'
        command: 'buildAndPush'
        Dockerfile: 'worker/Dockerfile'
        buildContext: 'worker'
        tags: |
          $(Build.BuildId)
          latest
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerTestCR'
        repository: 'fiegamitdockercomplex_nginx'
        command: 'buildAndPush'
        Dockerfile: 'nginx/Dockerfile'
        buildContext: 'nginx'
        tags: |
          $(Build.BuildId)
          latest
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Free Trial (d0a884f6-ea9b-4c9b-9e8f-8974e6263d0b)'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az container stop -g testRG -n multi-docker
          az container start -g testRG -n multi-docker
    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: 'Free Trial (d0a884f6-ea9b-4c9b-9e8f-8974e6263d0b)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'testRG'
        location: 'West Europe'
        templateLocation: 'Linked artifact'
        csmFile: 'azuredeploy.json'
        overrideParameters: '-imageRegistryPassword $(REGISTRY_PASS)'
        deploymentMode: 'Incremental'
